export type Lang = 'zh' | 'en';

export interface I18nDict {
  // 通用
  titleDefault: string;
  subtitle: string;
  version: string;
  generatedAt: string;
  generatedBy: string;
  searchTables: string;
  backToTop: string;
  toggleTheme: string;
  sidebarTitle: string;

  // 数据库信息
  statistics: string;
  databaseInfo: string;
  dbName: string;
  dbType: string;
  dbVersion: string;
  generateTime: string;

  // 统计
  tableCount: string;
  columnCount: string;
  tables: string;
  fields: string;

  // 表卡片
  tableOfContents: string;
  fieldsCount: string;
  primaryKey: string;
  foreignKey: string;
  uniqueKey: string;
  notNull: string;
  defaultValue: string;
  checkKey: string;

  // 表格列
  colNo: string;
  colName: string;
  colDataType: string;
  colNullable: string;
  colDefault: string;
  colConstraints: string;
  colDescription: string;
  yes: string;
  no: string;
  noData: string;

  // 子段
  fkRelations: string;
  fkName: string;
  fkColumn: string;
  fkRefTable: string;
  fkRefColumn: string;
  fkDeleteRule: string;
  fkUpdateRule: string;

  indexes: string;
  idxName: string;
  idxColumns: string;
  idxUnique: string;
  idxPrimary: string;

  // 表描述来源
  business: string;

  // 页脚
  footer: string;

  // ERD
  erdTitle: string;
  erdLegend: string;
  erdTable: string;
  erdRelation: string;
  erdOneToOne: string;
  erdOneToMany: string;
  erdManyToMany: string;
  erdNote: string;

  enumValues: string;
  autoGenerated: string;
}

export const I18N_ZH: I18nDict = {
  titleDefault: '数据字典',
  subtitle: '本文档由数据字典生成工具自动生成',
  version: '版本',
  generatedAt: '生成时间',
  generatedBy: '生成者',
  searchTables: '搜索表名...',
  backToTop: '回到顶部',
  toggleTheme: '切换主题',
  sidebarTitle: '📋 目录',

  statistics: '📊 统计信息',
  databaseInfo: 'ℹ️ 数据库信息',
  dbName: '数据库名称',
  dbType: '数据库类型',
  dbVersion: '数据库版本',
  generateTime: '生成时间',

  tableCount: '数据表',
  columnCount: '字段数',
  tables: '表',
  fields: '个字段',

  tableOfContents: '目录',
  fieldsCount: '个字段',
  primaryKey: '主键',
  foreignKey: '外键',
  uniqueKey: '唯一',
  notNull: '非空',
  defaultValue: '默认',
  checkKey: '检查',

  colNo: '#',
  colName: '字段名',
  colDataType: '数据类型',
  colNullable: '可空',
  colDefault: '默认值',
  colConstraints: '约束',
  colDescription: '说明',
  yes: '✓',
  no: '✗',
  noData: '-',

  fkRelations: '🔗 外键关系',
  fkName: '外键名',
  fkColumn: '字段',
  fkRefTable: '关联表',
  fkRefColumn: '关联字段',
  fkDeleteRule: '删除规则',
  fkUpdateRule: '更新规则',

  indexes: '📇 索引',
  idxName: '索引名',
  idxColumns: '字段',
  idxUnique: '唯一',
  idxPrimary: '主键',

  business: '📝 ',

  footer: '本文档由数据字典生成工具自动生成',

  erdTitle: '实体关系图 (ERD)',
  erdLegend: '图例',
  erdTable: '表',
  erdRelation: '关系',
  erdOneToOne: '一对一',
  erdOneToMany: '一对多',
  erdManyToMany: '多对多',
  erdNote: '外键关系连线，实线表示有明确的 FK 约束',

  enumValues: '枚举值',
  autoGenerated: '本文档由数据字典生成工具于'
};

export const I18N_EN: I18nDict = {
  titleDefault: 'Data Dictionary',
  subtitle: 'This document is auto-generated by Data Dictionary CLI',
  version: 'Version',
  generatedAt: 'Generated at',
  generatedBy: 'Generated by',
  searchTables: 'Search tables...',
  backToTop: 'Back to top',
  toggleTheme: 'Toggle theme',
  sidebarTitle: '📋 Table of Contents',

  statistics: '📊 Statistics',
  databaseInfo: 'ℹ️ Database Info',
  dbName: 'Database',
  dbType: 'DB Type',
  dbVersion: 'DB Version',
  generateTime: 'Generated',

  tableCount: 'Tables',
  columnCount: 'Columns',
  tables: 'tables',
  fields: 'columns',

  tableOfContents: 'Table of Contents',
  fieldsCount: 'columns',
  primaryKey: 'PK',
  foreignKey: 'FK',
  uniqueKey: 'Unique',
  notNull: 'NOT NULL',
  defaultValue: 'Default',
  checkKey: 'CHECK',

  colNo: '#',
  colName: 'Column',
  colDataType: 'Type',
  colNullable: 'Null',
  colDefault: 'Default',
  colConstraints: 'Constraints',
  colDescription: 'Description',
  yes: '✓',
  no: '✗',
  noData: '-',

  fkRelations: '🔗 Foreign Keys',
  fkName: 'Constraint',
  fkColumn: 'Column',
  fkRefTable: 'References Table',
  fkRefColumn: 'References Column',
  fkDeleteRule: 'On Delete',
  fkUpdateRule: 'On Update',

  indexes: '📇 Indexes',
  idxName: 'Name',
  idxColumns: 'Columns',
  idxUnique: 'Unique',
  idxPrimary: 'PK',

  business: '📝 ',

  footer: 'Auto-generated by Data Dictionary CLI',

  erdTitle: 'Entity Relationship Diagram (ERD)',
  erdLegend: 'Legend',
  erdTable: 'Table',
  erdRelation: 'Relation',
  erdOneToOne: 'One-to-One',
  erdOneToMany: 'One-to-Many',
  erdManyToMany: 'Many-to-Many',
  erdNote: 'Solid lines indicate explicit FK constraints',

  enumValues: 'Enum values',
  autoGenerated: 'This document was auto-generated by Data Dictionary CLI at'
};

export const I18N: Record<Lang, I18nDict> = {
  zh: I18N_ZH,
  en: I18N_EN
};

export function getI18n(lang?: Lang | string): I18nDict {
  const key = (lang === 'en' ? 'en' : 'zh') as Lang;
  return I18N[key];
}
